#pragma once

#define T_N "N"
#define T_S "S"
#define T_E "E"
#define T_W "O"

#define T_PRESS_KEY "App. sur boutton"
#define T_TO_REBOOT "pour redemarrer"
#define T_WILL_REBOOT "va redemarrer"
#define T_DEVICE "Dispositif"
#define T_TELESCOPE "Télescope"
#define T_FOCUSER "Focuser"
#define T_MOUNT "Monture"
#define T_MOUNTTYPE "Type de Monture"

#define T_LIMITS "Limites"
#define T_NOT_CONNECTED "pas Connecté"
#define T_TUNKOWN "Inconnue"
#define T_ERROR "ERREUR"
#define T_WARNING "ALERTE"
#define T_STAR "Etoile"
#define T_SLEWINGTO "Pointe vers" 
#define T_RECENTER "Recentre"
#define T_SELECTASTAR "Select. une Etoile"
#define T_FROMFOLLOWINGLIST "de la liste"
#define T_SELECTION "Selection"
#define T_ABORTED "Abandonné"
#define T_ALIGNMENT "Alignement"
#define T_FAILED "Echoué"
#define T_HASFAILED "a échoué"

#define T_GUIDERATE "Vit. Guidage"
#define T_MAXRATE "Vit. Max"
#define T_STARTED "Démarré"
#define T_STOP "Arrêt"
#define T_CANCEL "Annuler"
#define T_CANCELED "Annulé"
#define T_WRONG "Erroné"
#define T_NOTDEFINED "Non défini"
#define T_SUCESS "Réussi"
#define T_STARADDED "Étoile ajoutée"
#define T_VERSION "version"
#define T_YES "OUI"
#define T_NO "NON"
#define T_ON "Allumer"
#define T_OFF "Eteindre"
#define T_RESET "Remise à 0"
#define T_VALUE "Valeur"
#define T_SET "Envoyée"
#define T_GET "Recue"
#define T_DONE "fait"
#define T_TO "à"
#define T_LOW "Faible"
#define T_HIGH "Haut"
#define T_MIN "Min"
#define T_MAX "Max"
#define T_FACTORY "Usine"
#define T_DIRECT "Directe"
#define T_REVERSE "Inverse"
#define T_REVERSEDROTATION "Rotation Inversée"
#define T_DIRECTROTATION "Rotation Directe"
#define T_CONFIG "Config"
#define T_ROTATION "Rotation"
#define T_BACKLASH "Jeu"
#define T_GEAR "Réducteur"
#define T_RATIO "Réduction"
#define T_MICROSTEP "Micropas"
#define T_INSECONDS "en secondes"
#define T_MOTOR "Moteur"
#define T_STEPPER "Mt pp"
#define T_STEPS "Pas"
#define T_RESOLUTION "Résolution"
#define T_INCREMENTATION "Increment"
#define T_STEPSPERROT "Pas par Tour"
#define T_LOWCURR "Amp. Bas"
#define T_HIGHCURR "Amp. Haut"
#define T_CURRENT "Amperage"
#define T_PEAK "Pic"
#define T_MaxSlew "Vitesse Max"
#define T_Config "Config"
#define T_TIMESETTINGS "Param. Temps"
#define T_TELESCOPESETTINGS "Param. Telescope"
#define T_SHCSETTINGS "Param. Raquette"
#define T_SLEWSETTING "Param. Pointage"
#define T_MOTORSETTINGS "Param.  Moteur %u"
#define T_SHOWSETTINGS "Affiche Parametres"
#define T_FOCUSERSETTINGS "Param. Focuser"
#define T_DISPLAYSETTINGS "Param Écran"

#define T_ACCELERATION "Acceleration"

#define T_LATITUDE "Latitude"
#define T_LONGITUDE "Longitude"
#define T_AZIMUTH "Azimut"
#define T_ALTITUDE "Altitude"
#define T_DECLINAISON "Déclinaison"
#define T_RIGHTASC "Asc. Droite"
#define T_LOCALTIME "Heure Civile"

#define T_PARKPOSITION "Position Garage"
#define T_MAXPOSITION "Position Max"
#define T_MAXPOSITION2 "Pos. Max"
#define T_STARTPOSITION2 "Pos. Démar."

#define T_PARKPOSITION "Rangement"
#define T_GOTOPOSITION "Position AllerVers"
#define T_SYNCPOSITION "Sync Position"
#define T_MANUALSPEED "Vit. manuelle"
#define T_MANUALSPEED2 "Vit. manuelle2"
#define T_GOTOSPEED "Vit. AllerVers"
#define T_GOTOSPEED2 "Vit. AllerVers2"
#define T_ACCFORMAN "Acc. manuelle"
#define T_ACCFORMAN2 "Acc. manuelle2"
#define T_ACCFORGOTO "Acc. AllerVers"
#define T_ACCFORGOTO2 "Acc. AllerVers2"
#define T_DECFORMAN "Dec. manuelle."
#define T_DECFORMAN2 "Dec. manuelle2"

#define T_UNPARK "Utiliser"
#define T_PARK "Ranger"
#define T_HOME "Maison"
#define T_PARKED "Garé"
#define T_NOOBJECT "Pas d'Objet"
#define T_SELECTED "Selectionné"
#define T_FOCUSERACTION "Action Focuser"

#define T_SETPARK "Réglage Ranger"
#define T_ATHOME "à la maison"
#define T_UNLOCK "Dévérouillé"
#define T_LOCK "Vérouillé"
#define T_GOTO "AllerVers"
#define T_POSITION "Position"

#define T_SYNC "Synchroniser"
#define T_SYNCED "Synchronisé"
#define T_HOUR "Heure"
#define T_SYNCEDAT "Synchronisé à"
#define T_ALIGN "Aligner"
#define T_TRACKING "Poursuivre"
#define T_STARTTRAKING "Démarre Poursuite"
#define T_STOPTRAKING "Stop Poursuite"
#define T_TRAKINGSTATE "Etat Poursuite"
#define T_SIDEOFPIER "Coté du pied"
#define T_SAVE "Enregistrer"
#define T_SAVED "Enregistré"
#define T_Clear "Effacer"
#define T_SPIRAL "Spirale"
#define T_LX200COMMAND " Commandes LX200"
#define T_SETVEALUE "Regler Valeur"
#define T_GETVEALUE "Lire Valeur"
#define T_SETTARGET "Regler Cible"
#define T_TARGET "Cible"
#define T_TARGETIS "La Cible est"
#define T_TELESCOPEIS "Le Telescope est"
#define T_TELESCOPEEXCEED "Le Telescope dépasse"
#define T_SENSORLIMIT "Limite detecteur"
#define T_DECLIMIT "Limite DEC"
#define T_AZMLIMIT "Limite AZM"
#define T_BELOWHORIZON "Sous Horizon"
#define T_TELESCOPEMOTOR "Moteur Telescope"
#define T_OUTSIDELIMITS "Hors Limites"
#define T_FAULT "Défaut"
#define T_BUSY "Occupé"
#define T_CANTPARK "Rangement impossible"
#define T_CANTGOHOME "Maison impossible"

#define T_TELESCOPEACTION "Telescope Action"
#define T_SETSPEED "Réglage Vitesse"
#define T_SIDEREAL "Sidereal"
#define T_TIME "Temps"
#define T_SITE "Site"
#define T_SYNCWITHGNSS "Synchro GPS"
#define T_LUNAR "Lunaire"
#define T_SOLAR "Solaire
#define T_CLOCK "Horloge"
#define T_TIMEZONE "Fuseau horaire"
#define T_DATE "Date"
#define T_GNSSTIME "Temps GPS"
#define T_NOGNSS "Pas de GPS"
#define T_SIGNAL "Signal"
#define T_DISPLAY "Affichage"
#define T_BUTTONSPEED "Vitesse Bontons"

#define T_CONTRAST "Contraste"
#define T_TURNOFF "Eteindre"
#define T_SLEEP "Veille"
#define T_DEEPSLEEP "Veille Profonde"
#define T_PRESSSHIFTKEY "Appuyez sur Shift"
#define T_TOTURNON "Pour démarrer"
#define T_AFTER "après"
#define T_LOWCONTRAST "Contraste faible"
#define T_TURNDISPLAYOFF "Arrêter affichage"


#define T_BUTTONSPEED "Vitesse Bontons"
#define T_SLOW "Lent"
#define T_MEDIUM "Moyen"
#define T_FAST "Rapide"

#define T_SITEELEVATION "Altitude Site"
#define T_HORIZON "Horizon"
#define T_HORIZONLIMIT "Limite Horizon"
#define T_OVERHEAD "Au dessus"
#define T_OVERHEADLIMIT "Limite au dessus"
#define T_MERIDIANE "Meridien E"
#define T_MERIDIANW "Meridien O"
#define T_MERIDIANLIMIT "Limite Meridien"
#define T_MERIDIANLIMITE "Limite Meridien E"
#define T_MERIDIANLIMITW "Limite Meridien O"

#define T_MAXHOURANGLE "Angle horaire max"
#define T_UNDERPOLE "Sous le Pôle"
#define T_UNDERPOLELIMIT "Limite sous le Pôle"

#define T_CURRENTLYTRACKING "Poursuite en cours"
#define T_CANNOTBECHANGED "modification impossible"
#define T_INITIALISATION "Initilisation"
#define T_THEMOUNTMUSTBEATHOME1 "La monture doit"
#define T_THEMOUNTMUSTBEATHOME2 "être réglée à"
#define T_THEMOUNTMUSTBEATHOME3 "la position maison."
#define T_READYFOR "Prêt pour"
#define T_MOUNTSYNCED "Monture synchronisée"
#define T_HANDCONTROLLER "Raquette"
#define T_MAINUNITINFO "Info Unité Centrale"
#define T_SHOWVERSION "Afficher Version"
#define T_REBOOT "Redémarrer"
#define T_RESETTOFACTORY "Réglage Usine"
#define T_FIRMWAREVERSION "Version Programme"
#define T_GERMANEQUATORIAL "Allemande Equatoriale"
#define T_EQUATORIALFORK "Equatoriale à Fourche"
#define T_ALTAAZIMUTAL "Altazimutale"
#define T_ALTAAZIMUTALFORK "Fourche Altazimutale"

#define T_TURNWIFIOFF "Eteindre Wifi"
#define T_TURNWIFION "Allumer Wifi"
#define T_SHOWPASSWORD "Montrer mot de passe"
#define T_SELECTMODE "Choisir un Mode"
#define T_SHOWIP "Montrer IP"
#define T_PASSWORDIS "Le mot de passe est"
#define T_ACCESPOINT "Point dAccès"
#define T_WIFIINTERFACE "Interface Wifi"
